name: Deploy Laravel Classes Microservice

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - microservice-energym-classes/**
      - .github/workflows/microservice-energym-classes-deploy.yml
      - docker-compose.yml
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ADDRESS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          command_timeout: 200m
          script: |
            cd energym
            git pull origin main
            docker-compose up -d --build microservice-energym-classes
            echo 'Classes Service Updated'
