name: Deploy Laravel Auth Microservice

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - microservice-energym-auth/**
      - .github/workflows/laravel-subspace-authentication-deploy.yml
      - docker-compose.yml
      - Dockerfile


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/web-subspace
            git pull origin master
            docker-compose up -d --build microservice-energym-auth
            echo 'Laravel Auth Service Updated'
